### ISSUE TITLE
05/23 회의록 및 TODO

### ISSUE THREAD

**Issue by swimmie0** [swimme/react-diary-client#10]
- 다음 회의 일정 5/31 (월) 오후 6시

# TODO
## Backend
- [x] ~~로그인 / 이수영 /~~ https://github.com/swimme/react-diary-client/pull/7
- [x] 게시글 CRUD api 개발 / 이수영 / https://github.com/swimme/react-diary-client/pull/13
- [ ] 네이버 api 사용/ 이수영

## Frontend  
- [x] ~~로그인 / 이수영 /~~ https://github.com/swimme/react-diary-client/pull/8
- [ ] 글작성 페이지 기능연동 (에디터) / 이수영
- [x] ~~글 보기 페이지 완성 / 고주연 /~~ https://github.com/swimme/react-diary-client/pull/9
- [x] 메인 페이지 레이아웃 + pagination (w/ mock-data) / 윤정인 / https://github.com/swimme/react-diary-client/pull/14

## Etc
- [x] ~~프로젝트 계획 ppt 제작 / 윤정인~~
- [x] ~~프로젝트 계획 발표 / 고주연~~
- [x] ~~api 인터페이스 문서작성 / 이수영 /~~ [api docs](https://github.com/swimme/react-diary-client/wiki/%EB%8B%A4%EC%9D%B4%EC%96%B4%EB%A6%AC-api-%EB%AC%B8%EC%84%9C)

### later
- 로그인 페이지 레이아웃
- 캘린더 오픈소스 삽입

**Comment by swimme** [comment]
기능 우선순위
1. 글쓰기수정삭제 개발 및 연동
2. 에디터 오픈소스 사용 + api
3. 게시글 페이지네이션, 검색, 기분별 
4. 캘린더 ui ← 기능없이

---
이후에 
- 검색 기능 최적화 (debounce) 
- 이미지업로드
- 캘린더 ui에 api 연동
- 에디터 커스텀
- 인라인 사용자정보수정

**Comment by swimmie0** [comment]
## 5/27 피드백
- 기능 구체화가 아직 덜 된 느낌. 우선순위 정하기
- **사용자들이 해당 기능을 썼을 때 얻는 가치 고려해보면서 만들기**
  - 무엇을 위해서 이 기능을 만드는지 + 어떻게 나타내고 싶은지 

- 투두 회의록, 아이디어 등 Notion -> github으로 관리하기
- PR: 개발 결과 + 개발하며 발견한 사이트나 힘들었던 내용, 오류잡는 내용 등 도 있었다면 쓰는걸 추천 

<br></br>
- 에디터 오픈소스 추천
   - [draftjs](https://draftjs.org/) (ssr 지원, 한글 issue)
   - tui (ssr 지원x) 
   - ssr 지원 안하는 오픈소스 라이브러리들 꽤잇음 (ssr말고 csr에서 동작하게끔 하는 방법..)
- commit 은 모두 완성된 코드만!
- 기존 progress는 schema 설계 - 백엔드 기획 - ui (프론트엔드) 
- 마무리 잘.. 🤗

**Comment by swimmie0** [comment]
[칸반보드](https://github.com/swimme/react-diary-client/projects/1) 보다 이슈가 글쓰기 편한 거 같아서 여기에 만들어봤습니당
앞으로 회의록, todo 외에 작업단위나 내용 공유 등등 라벨링해서 자유롭게 올려주시면 될거 같아요 !

**Comment by swimme** [comment]
> [칸반보드](https://github.com/swimme/react-diary-client/projects/1) 보다 이슈가 글쓰기 편한 거 같아서 여기에 만들어봤습니당
> 회의록, todo 외에 작업단위나 내용 공유 등등 라벨링해서 자유롭게 올려주시면 될거 같아요.
