### ISSUE TITLE
05/31 회의록 및 TODO

### ISSUE THREAD

**Issue by swimmie0** [swimme/react-diary-client#16]
> 다음 주 회의 6/6 저녁 ~~7시~~10시

# TODO 
> 기능 연동

## 다이어리 작성 페이지 
  - [x] 에디터 + 네이버 api/ 이수영 / https://github.com/swimme/react-diary-client/pull/21
  
## 다이어리 메인 페이지
  - [x]  paginate 연동 / 이수영 / https://github.com/swimme/react-diary-client/pull/23
  - [ ] 검색 기능 api 연동 / 윤정인 
  - [x] 기분별 개수 표시 / 이수영

## 다이어리 상세 페이지
  - [x] 다이어리 목록 뷰 추가  / 고주연 / https://github.com/swimme/react-diary-client/pull/22
  - [ ] 다이어리 기능 연동 (수정, 삭제)  / 고주연 

### Later
- 다이어리 수정 페이지 
- 로그인 페이지 (버튼 하나만) 
- 이미지 업로드 기능
- 캘린더 ui 오픈소스 삽입
- 추가) 기분별 개수 누르면 -> 조회 페이지로 이동

**Comment by swimmie0** [comment]
[5/27 피드백 참고](https://github.com/swimme/react-diary-client/issues/10#issuecomment-849438388)

**Comment by swimmie0** [comment]
6/3 피드백

- 구현 완성 빠르게 하는 것이 좋음
- 데이터 플로우 문서화
- PR 자세히
- 상태관리 툴 리덕스 필요성 못느끼면 안써도 된다. 대신 react-query 사용이유 좀더 명확히 하기
- 기타 : 현업툴 storybook
- 프로젝트외 공부: js 코어, 기본기가 중요
