### ISSUE TITLE
06/06 회의록 및 TODO

### ISSUE THREAD

**Issue by swimmie0** [swimme/react-diary-client#24]
> 다음 주 회의 6/12 7시

# TODO 
> 기능 연동 + 리팩토링 계속

## 로그인 페이지
  - [x] 로그인 페이지 / 고주연 #28 

## 다이어리 상세 페이지
  - [x] 다이어리 기능 연동 (수정, 삭제)  / 고주연 #22 (+수정페이지 이동 updatePost 함수에서 경로 수정해야 함)

## 다이어리 메인 페이지
  - [ ] 검색 기능 api 연동 / 윤정인 

## 다이어리 작성 페이지 
  - [ ] 에디터 상태 관리, 성능, 정렬 툴 보충 등.. 리팩토링 / 이수영

## 다이어리 수정 페이지
  - [x] 수정 페이지 / 이수영 / https://github.com/swimme/react-diary-client/pull/30

## 사이드바 or 메인페이지 상단
  - [ ] 기분별 개수 누르면 -> 조회 페이지로 이동 / 윤정인

### Later
- 상태관리 리덕스 도입
- 캘린더 ui 오픈소스 삽입 +추가) 기능 연동 / 이수영 -> 하는 중 
- 이미지 업로드 기능
- 사용자 정보 수정

## 기타
- 후순위 기능 시간 여유있는 사람이 자유롭게 (하기 전 알려주기)
- 글보기 페이지: 이전글, 다음글 id 받아오기?
- 리덕스 사용 (상태관리)
- 시험기간😭

**Comment by dewyeon** [comment]
6/10 멘토링
- 다이어리 자체에 대한 기능은 어느정도 완성되었는데, 우리의 다이어리 서비스만의 차별점에 대한 기획 필요할 것 같다
  - ‘기분’ 다이어리에 대한 차별점?
  - 캘린더 아이디어 괜찮은 것 같은데 사이드바에 넣기보다는 캘린더는 좀 더 커야 좋을 것 같고
  - 사이드바 비어있으니까 넣을 내용이 딱히 없으면 굳이 없어도 괜찮을 듯 (비어있는 것보다는 없는게 낫다)
    - 없앤다면 글쓰기버튼을 아예 위쪽에 넣는다던지 등등
  - 사용자는 위->아래, 왼->오로 화면을 본다 
    - 화면 구성과 흐름을 기능과 연결해서 생각해보기?
- 구글 개발자 도구 이용해서 렌더링에 걸리는 시간 측정 및 성능 확인
- 글 상세 페이지에서 이전글, 다음글 id 문제: 이전글과 다음글 id를 목록 페이지에서 같이 넘겨주기가 가장 좋을 것 같고 안되면 +-1보다는 (보안문제도 있고 삭제문제도 있다) 모든글을 다 가져와서 이전글과 다음글 계산하기 (성능은 안좋겠지만)

**Comment by swimmie0** [comment]
## 기분 다이어리 차별점 관해 나온 아이디어

1.  메인페이지에 캘린더 + 날짜별 기분 볼 수 있는 기능
2.  게시글 기분에 따른 테마 색깔 변경 
3.  random 응원 메세지 출력
4.  템플릿 기능

## 에디터 피드백
- 책검색 modal 화? 좀더 큰 창이 더 나을듯 하다
- 책검색 검색전 빈화면 채우기 : 베스트 셀러 등 
    - 베스트셀러: 네이버 api 없음 / 알라딘, 인터파크 api  또는 크롤링 방법
    - 삽화로 채우기? 우선 placeholder로 채움
