### ISSUE TITLE
06/12 회의록 및 TODO

### ISSUE THREAD

**Issue by swimmie0** [swimme/react-diary-client#29]
## 논의
- 다이어리 작성시 날짜 지정 할 수 있도록 할지
- 메인 페이지 레이아웃.. (캘린더, 기분통계, 사이드바, 검색 배치)
- 참고 https://github.com/swimme/react-diary-client/issues/24

## TODO 
- comment로

**Comment by wjddls0828** [comment]
(정인)
- [x] 게시글 기분에 따른 테마 색깔 변경: 가장 최근 moodId 가져오기
- [x] random 응원 메세지 출력: 가장 최근 moodId별로 할지 그냥 일반으로 할지
- [x] 글 목록 보기 무드 이모티콘 보이기

- [x] 검색 기능 API 연동
- [x] 기분별 개수 누르면 -> 조회 페이지로 이동

**Comment by swimmie0** [comment]
>  0616 updated!

수영
- [x] 캘린더 기능 완성 / https://github.com/swimme/react-diary-client/issues/29
   - 클릭시 상세 이동 ✔️
   - 글많아질 경우 오류나는 상황 잡기 ✔️ (css 떄문이었음..!)
   - +) 다른 날짜 글 쓰기 (오늘 이전 날짜만 가능해야함..) (✖️ 후순위)
<img width="200" alt="스크린샷 2021-06-16 오후 5 27 23" src="https://user-images.githubusercontent.com/37537202/122185525-208fad00-cec8-11eb-8181-70c388f7795b.png">

(금~일) 
- [ ] 에디터 기능) 상세페이지에서 북카드 clickable / 에디터 이슈 고치기, ui 
- [ ] 오류상황 핸들 (url 대응 등), 서버포함
- [ ] 상태관리 추가

그 외 
- ui 보충 - 폰트 적용 / 사파리css...
- 상태관리 고민 (react-query for data caching? redux for global state?)
- 에디터 툴 보충 (정렬 / 이미지 업로드 <- 시간된다면)

논의해야 할 내용
- 화면 배율..? 전체적으로 크기가 너무 큰건지?
- 메인페이지 레이아웃

**Comment by swimme** [comment]
참고 https://github.com/swimme/react-diary-client/issues/24

**Comment by dewyeon** [comment]
주연

- [ ] 글 상세 페이지에서 이전글/다음글 id 받아오기 문제 해결
- [ ] 다른 글 보기 연동

+) 
- 존재하지 않는 id의 글일 경우, 상세페이지에 접속했을 때 '존재하지 않는 글입니다' 등 표시
- 최종 보고서에 들어가야 할 내용 정리 시작

**Comment by dewyeon** [comment]
> * 다이어리 작성시 날짜 지정 할 수 있도록 할지
***
이 부분 회의때는 다이어리라는 특성상 날짜 지정하는 것도 좋을 것 같다고 의견 냈었는데요, 지금 생각하니까 그렇게 되면 
- 글 작성 페이지에서 글 작성 날짜를 지정할 수 있는 칸이 따로 필요할 것 같고, 
![캡처](https://user-images.githubusercontent.com/44095036/121810906-7cc2b900-cc9d-11eb-9ee8-d4637f5edfe8.PNG)

![asd](https://user-images.githubusercontent.com/44095036/121810943-9ebc3b80-cc9d-11eb-992f-ddcdb4bca7ca.PNG)
(이런식으로 ..?)

- 다이어리의 createdAt 항목도 글 작성 시점이 아니라 사용자가 지정한 날짜가 들어가도록 변경해야 하고 

등등 생각보다 할일이 더 늘어날 것 같아서, 시간 부족하면 그냥 넣지 않는것도 괜찮을 것 같다는 생각이 듭니다 ,,,

**Comment by swimmie0** [comment]
> > * 다이어리 작성시 날짜 지정 할 수 있도록 할지
> 
> 이 부분 회의때는 다이어리라는 특성상 날짜 지정하는 것도 좋을 것 같다고 의견 냈었는데요, 지금 생각하니까 그렇게 되면
> 
> * 글 작성 페이지에서 글 작성 날짜를 지정할 수 있는 칸이 따로 필요할 것 같고,
>   ![캡처](https://user-images.githubusercontent.com/44095036/121810906-7cc2b900-cc9d-11eb-9ee8-d4637f5edfe8.PNG)
> 
> ![asd](https://user-images.githubusercontent.com/44095036/121810943-9ebc3b80-cc9d-11eb-992f-ddcdb4bca7ca.PNG)
> (이런식으로 ..?)
> 
> * 다이어리의 createdAt 항목도 글 작성 시점이 아니라 사용자가 지정한 날짜가 들어가도록 변경해야 하고
> 
> 등등 생각보다 할일이 더 늘어날 것 같아서, 시간 부족하면 그냥 넣지 않는것도 괜찮을 것 같다는 생각이 듭니다 ,,,

넵 만약 만들게 된다면
1. 디비 추가시 default createdAt 삭제
2. 클라이언트에 날짜입력 상태 추가
  - 입력 폼은 prime-react 의 calendar form 
3. 오늘 이후의 날짜는 작성하지 못하게 Unable 
  - 오늘 날짜를 구해서 이후 날짜배열은  prime-react 의 calendar form 의 disabledDates 속성에 넣기

위와 같은 절차? 를 거쳐야 해서, 그럼 이건 가장 후순위로 미룰게요!
