### ISSUE TITLE
06/18 회의록 및 TODO

### ISSUE THREAD

**Issue by swimmie0** [swimme/react-diary-client#33]
> 06/20 일 10pm

**Comment by dewyeon** [comment]
- [x] 로그인페이지 레이아웃과 커밋일부 수정 -> 이후 바로 merge하기로
- [x] 글 상세 페이지 UI 다듬기
  - 일기장 같은 느낌 더 나게
    -  moodId와 글 작성 날짜 있는 칸 배경색 수정: mood icon이랑 어울리는 색으로 moodId값에따라 바뀌도록? 아니면 흰색에 테두리만? (삭제버튼처럼)
- [x]  global 폰트 적용 (sunflower, 나눔고딕 등)
- [x] 글 상세페이지에서 다른 글 목록 보기 -> 다이어리 메인화면의 <글 목록 및 페이지네이션>을 하나로 컴포넌트화해서 가져오기

**Comment by swimmie0** [comment]
- [x] 로그아웃 버튼 추가, 기능 연동 ✔️
- [x] 에디터 기능  ✔️ 
    - 책검색창 ui 수정 (하단 슬라이드창으로) 
    - 에디터 ui 손보기
    - 상세페이지에서 북카드 ui  ~~clickable~~
    -  에디터 이슈 고치기
- [x] 오류상황 핸들 (url 대응 등), 서버포함 ✔️ 
- [ ] 상태관리

그 외 
- [x] ui 보충 - 사파리css...
- 상태관리 고민 (react-query for data caching? redux for global state?)
- 배포 시도
- 에디터 툴 보충 (정렬 / 이미지 업로드 <- 시간된다면)

**Comment by wjddls0828** [comment]
1. 무드 아이디에 맞게 응원메세지 출력, 하루에 하나만 출력되게
2. 검색창 사이드바로/ 검색 api
3. 글목록 볼 때 날짜 볼 수 있게
4. 기분별 조회 기능(API 수정)
5. 기분별 테마 변경

**Comment by wjddls0828** [comment]
![image](https://user-images.githubusercontent.com/58072776/122550008-1d362600-d06e-11eb-9be4-b1de093aca2e.png)
주연님! 제가 책을 첨부해서 글을 썼는데 상세페이지에는 그 첨부한 책이 안뜨는데 그 부분도 수정해주셔야 할 것 같아요!

**Comment by wjddls0828** [comment]
> ![image](https://user-images.githubusercontent.com/58072776/122550008-1d362600-d06e-11eb-9be4-b1de093aca2e.png)
> 주연님! 제가 책을 첨부해서 글을 썼는데 상세페이지에는 그 첨부한 책이 안뜨는데 그 부분도 수정해주셔야 할 것 같아요!

![image](https://user-images.githubusercontent.com/58072776/122550122-4656b680-d06e-11eb-86ca-24cfdd8365d3.png)
다시 수정페이지 들어가면 첨부한 책이 보이네요!

**Comment by dewyeon** [comment]
> ![image](https://user-images.githubusercontent.com/58072776/122550008-1d362600-d06e-11eb-9be4-b1de093aca2e.png)
> 주연님! 제가 책을 첨부해서 글을 썼는데 상세페이지에는 그 첨부한 책이 안뜨는데 그 부분도 수정해주셔야 할 것 같아요!

- 넵 이부분은 에디터뷰어를 담당하신 수영님이 확인해주셔야 할 것 같습니다 ㅠㅠ
***
- 그리고 정인님 혹시 https://github.com/swimme/react-diary-client/pull/31#discussion_r654261573 이 부분 제가 회의에서 말씀드린대로 컴포넌트로 빼는것 가능할까요? 글 상세페이지에서 활용하려고 해서요! 만약 다른태스크 바쁘시다면 해당 pr 머지되면 제가하겠습니다
![aaaaa](https://user-images.githubusercontent.com/44095036/122554932-90429b00-d074-11eb-80fb-bbf174df3791.PNG)
이 DiaryListContainer로 감싸져있는 노란색 부분 입니다!

**Comment by swimmie0** [comment]
@dewyeon @wjddls0828  에디터 뷰어 책컴포넌트 안보이는 문제확인했습니다~ 에디터뷰어의 `blockRenderFn` prop으로 `useEditorCustomBlock` hook의 `renderCustomBlock`함수를 넘겨줘야 합니다. 커스텀 블럭을 렌더하는 함수로, 코드 추가해보시면 됩니다! 수정사항 함께 PR할게요.
